spring.application.name=A2Mussab

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:moviedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enables the H2 console so you can view your tables at /h2-console
spring.h2.console.enabled=true
# Required to handle the Movie entity auto-generation
spring.jpa.hibernate.ddl-auto=update